### ISSUE TITLE
Crash on iPhone4s/iOS7

### ISSUE THREAD

**Issue by marcanw** [myflashlab/PermissionCheck-ANE#1]
I just bought this ane but I can't use it. 
Everything works fine on iOS9 but I tried on a iPhone 4s / iOS7 and the ane crash the app at the launch. Even if the ane is never called I have the same issue. The only way to avoid the crash is to retrieve the ane.
I tried with air 22.0.153 and air 23.0.230
Moreover if I try to publish with air 19.0.241, I get the following error
![image](https://cloud.githubusercontent.com/assets/21979056/18228530/d292a12e-7252-11e6-9152-e09a9c5a29ff.png)
Can you help me out?
Thank you.

**Comment by myflashlab** [comment]
As stated in the [requierments](https://github.com/myflashlab/PermissionCheck-ANE#requirements) section, the ANE works on iOS8+

**Comment by marcanw** [comment]
I can understand that it is ios8+ but a crash at the launch of the app is a bit short. For android it would be doable with multiple apk but not on ios.
At least a flag isSupported might be more appropriate otherwise it means 2-3 % of my users won't be able to use the next release. For this functionality it doesn't worth it.

**Comment by myflashlab** [comment]
I'm marking this as an enhancement. It would be a good idea to add a method in all ANEs to return ```true``` or ```false``` if the min requirements are met or not. Thanks for pointing this out.

**Comment by marcanw** [comment]
Do you have a time frame or a workaround for this?
I can't use the ane while it crashes the app on ios7-
Thank you.

**Comment by myflashlab** [comment]
We have developed a new ANE which will solve this problem on all of our ANEs not just this one. That's why it took us some time to reply back. But the result is awesome. the new ANE will be free and available on Github. we will upload the new repository in a couple of days. However, you can check out the asdoc [here](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/inspector/Inspector.html). Real samples and demo projects will be uploaded soon.

**Comment by marcanw** [comment]
Great :-)
Thank you

**Comment by myflashlab** [comment]
https://github.com/myflashlab/ANE-Inspector-Tool

**Comment by mrfrasier** [comment]
Hello,

The Inspector is nice, but it would seem to be useless here. Simply having the ANE present in the project causes the IPA to crash on iOS 7. I was under the impression it should only crash if I try to instantiate it, and that the purpose of the Inspector ANE was to check to see if you were in the right environment to do so?

**Comment by marcanw** [comment]
Yes same here. Actually it crashes the app on ios7 just by being present in the project. So Inspector is useless for me too :-(
You can't just do an ane that doesn't crash on ios7 even if it doesn't work?

**Comment by mrfrasier** [comment]
Agreed. I don't see the point of the Inspector if it's going to crash just being present.

**Comment by myflashlab** [comment]
Ok, this is interesting. we'll investigate this more and update you a.s.a.p.

**Comment by marcanw** [comment]
Yes please keep me posted. I already bought this ane.
I'd like to use it in my next release but I can't.

**Comment by myflashlab** [comment]
Please test this version: [permissionCheck-test-version.zip](https://github.com/myflashlab/PermissionCheck-ANE/files/478054/permissionCheck-test-version.zip) It shouldn't cause a crash any more. Then when your app runs, use the inspector ANE to check the environment and avoid initializing it if the inspector returns false.

If your app still crashes, please connect your device to a mac and send me the crash log printed to the xcode debug console.

Let us know how it goes.

**Comment by marcanw** [comment]
Yep. It doesn't crash on ios7 now :-)
Why would I add inspector while I can just do a test on the ios version?

**Comment by myflashlab** [comment]
> Why would I add inspector while I can just do a test on the ios version?

You don't have to :) We will submit a new version of this ANE on Monday so you can grab the commercial version.

**Comment by marcanw** [comment]
Thank you.
I'll finally be able to use it on my next release :-)

**Comment by marcanw** [comment]
Also I have question.
Does this ane also work for android. I ask it because android is mentioned in the  docs but the commercial info talks about ios only.

**Comment by myflashlab** [comment]
You should be able to understand how permissions are treated on Android in AIR by reading this post: http://www.myflashlabs.com/understanding-android-ios-permissions-in-adobe-air-apps/

**Comment by marcanw** [comment]
ok so the android part won't need any particular handling right now; What about the new release of air 23?

**Comment by myflashlab** [comment]
V1.0.1 is released now. And we have not yet tested AIR 23 for permissions. My guess is that Adobe has not added Android SDK 23 compilation because that's a big change and nothing has been mentioned is the release notes. If we find anything other than my guess above, I will update this post.

**Comment by marcanw** [comment]
As a buyer of the 1.0.0,  how do I get the new version?

**Comment by myflashlab** [comment]
simply login to http://www.myflashlabs.com/my-account/ and download the latest version. And by the way, AIR 23 is still using the older version of Android SDK so you won't need the permission check for your Android app at all at the moment.

**Comment by marcanw** [comment]
I can't
ERROR: Login failed because your IP address has been blocked. Please contact the administrator.
