### ISSUE TITLE
app flickers and disappears from view, debugger not started and no console logs

### ISSUE THREAD

**Issue by syberkitten** [myflashlab/PermissionCheck-ANE#10]
Hi
I wasn't been able to use the ANE
it simply makes the app disappear after it starts.
tested on both android 5 and 6.

The app appears in the task list but switching to it
just shows the "desktop" as if the app is minimized immediately.

I've reverted to handling the permissions manually, and it works
seamlessly.

**Comment by tpntpn** [comment]
I have a similar problem when compiling with the AIR 25.0 for IOS. Instead of bringing up the permission screen, the app silently disconnects from the debugger and shuts down. AIR 24.0 does not appear to have the same problem.

**Comment by myflashlab** [comment]
@tpntpn We have tested the ANE with AIR 25 and it works fine! Are you sure you have included the permission reason string? https://github.com/myflashlab/PermissionCheck-ANE/blob/master/FD/application.xml#L108-L140

@syberkitten Are you experiencing this on iOS or Android?

**Comment by tpntpn** [comment]
Thanks for the pointer. This  (IOS) problem was fixed by setting the appropriate permission reason string.

**Comment by myflashlab** [comment]
@syberkitten let us know more information about what you are experiencing.

**Comment by notmark** [comment]
Experiencing this same issue on SDK 25 and SDK 26 Beta. No errors thrown. Manifest contains everything from the doc.

**Comment by myflashlab** [comment]
Please send us any error messages from AndroidStudio logcat console.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
