### ISSUE TITLE
IOS permissionState check not working

### ISSUE THREAD

**Issue by allanwcox** [myflashlab/PermissionCheck-ANE#16]
var c:PermissionCheck = new PermissionCheck();
var permissionState:int = c.check(PermissionCheck.SOURCE_LOCATION);
on IOS permissionState always comes back as 0 even the first time which should be unknown "3".
even after going into settings and allowing location for the app it still comes back as 0. 
It is working correctly on Android.

**Comment by myflashlab** [comment]
SOURCE_LOCATION works for the Android side only. for the iOS, you must use the following:

PermissionCheck.SOURCE_LOCATION_WHEN_IN_USE  
PermissionCheck.SOURCE_LOCATION_ALWAYS  

Make sure you are upgrading to the latest version of the ANE.
