### ISSUE TITLE
Error with library.swf: incompatible with the applications namespace or root SWF

### ISSUE THREAD

**Issue by guzur** [myflashlab/PermissionCheck-ANE#17]
Hi,

I recently purchased this ANE and I can't compile my test APP with Animate CC. 

It throws this message:

`Error: The extension com.myflashlab.air.extensions.permissionCheck has either a namespace version or library.swf with a version that is incompatible with the applications namespace or root SWF.`

I'm using AIR SDK 25 and I added in the manifest `<uses-sdk android:targetSdkVersion="23"/>`.

Any idea of what is happening?

Thank you very much.

**Comment by myflashlab** [comment]
When you are using AIR 25, why don't you set the namespace to 25? check this out: https://github.com/myflashlab/PermissionCheck-ANE/blob/master/FD/application.xml#L2

Besides that, you should also set the -swf-version to 36. check this out: https://stackoverflow.com/questions/9537076/chart-of-swf-versions-to-flash-versions

**Comment by myflashlab** [comment]
let us know if this issue is solved now?

**Comment by guzur** [comment]
Yes, thank you, but now I have this error:

`ArgumentError: Error #3500: The extension context does not have a method with the name command.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.myflashlab.air.extensions.nativePermissions::PermissionCheck/check()`

Any idea what's wrong?

**Comment by myflashlab** [comment]
this error ususally means that the ane is not correctly embedded in your project OR maybe you are trying to run it on a simulator? you may find these videos helpful: https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by myflashlab** [comment]
please let us know if you have this problem yet?

**Comment by informeduc** [comment]
Besides, how and where can I set the -swf-version to a specific value?
The ANE I'm trying to use requires swfVersion 29 and the current active in FlashBuilder 4.6 seems to be swfVersion 14.
