### ISSUE TITLE
Adobe Animete CC to IOS 10

### ISSUE THREAD

**Issue by abun81** [myflashlab/PermissionCheck-ANE#18]
Hi, I'm trying your demo , simply debug main.as on my iPad from adobe cc animate & got this error. 

![screen shot 2017-08-15 at 12 31 22 am](https://user-images.githubusercontent.com/305523/29283857-98274930-8152-11e7-8d7b-9f95be018652.png)

**Comment by myflashlab** [comment]
you are missing the dependency ANEs. check this out: https://github.com/myflashlab/PermissionCheck-ANE/tree/master/AIR/lib

to be more exact, you are missing overrideAir.ane on iOS.
