### ISSUE TITLE
Feature: Detect if notifications have been disabled

### ISSUE THREAD

**Issue by mrfrasier** [myflashlab/PermissionCheck-ANE#2]
Hello,

Is it possible to add a check to see if users have previously disabled notifications for your app? This way we can notify and send them to settings should they decide to re-enable them.

Thanks!

**Comment by ikuprin** [comment]
Hi.

What about this question? It's highly likely functionality for our app...

**Comment by myflashlab** [comment]
Yes, this is in our to-do list and will add it to the ANE soon when the new version is ready. We have been working on many new updates recently and this one is also on the list.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
