### ISSUE TITLE
Request new permission suport

### ISSUE THREAD

**Issue by SaleemEM** [myflashlab/PermissionCheck-ANE#21]
Before opening a new issue, make sure you are using the latest available ANE. If the ANE is dependent on other libraries or dependencies, also make sure they are the latest versions.

## Environment ##
* Android API Version: OS 6 and above
* iOS Version:
* AIR SDK Version: 28

## Problem Description ##
Need new permission support
* Copy your manifest ```.xml``` file.
<uses-permission android:name="android.permission.c2dm.permission.RECEIVE"/>
<uses-permission android:name="android.permission.com.permission.C2D_MESSAGE"/>
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
<permission android:name="air.[[private]].permission.C2D_MESSAGE" android:protectionLevel="signature" />
<uses-permission android:name="air[[private]].permission.C2D_MESSAGE" />

**

- uses-permission android:name="android.permission.c2dm.permission.RECEIVE"
- uses-permission android:name="android.permission.com.permission.C2D_MESSAGE"
- uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"
- permission android:name="air.[[private]].permission.C2D_MESSAGE" android:protectionLevel="signature"
- uses-permission android:name="air[[private]].permission.C2D_MESSAGE"

**

**Comment by myflashlab** [comment]
please explain more. I couldn't understand the question.
