### ISSUE TITLE
Problem writing a file on Android 8.0

### ISSUE THREAD

**Issue by guzur** [myflashlab/PermissionCheck-ANE#23]
Hi,
We have an error when we try to write a file on Android 8.0 on desktopDirectory (on AIR 30.0).
ANDROID 7.0:  It works without any problem.
ANDROID 8.0:  I tested on 2 different moviles and I get this error:  'Error #3001: File or directory access denied.'
NOTE 1:  On applicationStorageDirectory it works without any problem on both versions.

NOTE 2:  When reading files it works without any problem on both versions.

## Environment ##
* Android API Version: 8.0
* iOS Version:
* AIR SDK Version: 26, 28 and 30

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
