### ISSUE TITLE
How to detect iOS Wireless Data setting for the game 

### ISSUE THREAD

**Issue by jimmymjing** [myflashlab/PermissionCheck-ANE#24]
on iOS users could set wireless data allowance for a specific app to Off, WLAN or WLAN& cellular Data. Is there a way that I could check this setting when the user enters my game? I see some games would show a popup and direct users to the iphone's settings. 

I'm a member of myflashlabs and checked the Permission ANE, but it doesn't have a permission check for "Wireless Data"...

**Comment by myflashlab** [comment]
When you turn cellular off for a specific app, the OS will automatically show a popup when you run the app. There's nothing you would need to do on your side.

This feature is really not what the permission ANE is supposed to cover. However, please check [this page](https://stackoverflow.com/questions/48194863/ios-detect-setting-of-system-settings-cellular-cellular-data-master-switch) and if you think you really need it, maybe you can order a custom ANE development for it?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
