### ISSUE TITLE
Missing Purpose String in Info.plist File - NSContactsUsageDescription, NSCalendarsUsageDescription

### ISSUE THREAD

**Issue by apofis1969** [myflashlab/PermissionCheck-ANE#25]
## Environment ##
* Android Version:
* iOS Version: 12.1
* AIR Version: 31

## Problem Description ##
The app has been rejected from testflight because of missing NSContactsUsageDescription, NSCalendarsUsageDescription
But we did not ask for this permission. only camera and microphone. Is this a bug with iOS 12.1 and AIR SDK 31?

**Comment by myflashlab** [comment]
This has been discussed before. Please refer here: https://github.com/myflashlab/PermissionCheck-ANE/issues/14
