### ISSUE TITLE
Android?

### ISSUE THREAD

**Issue by marcanw** [myflashlab/PermissionCheck-ANE#3]
Last versions of android are getting more aggressive about permissions.
The number of permissions issues are skyrocketing on android the last weeks.
Unfortunately I have no means to detect them and to open the appropriate settings.
What's puzzling me is that the ref doc talks about android but I din't know if it's working because the commercial version only talks about iOS.
Any chance to create a android permission ane?
I'd be ready to buy a new one or to pay an upgrade for this.
Thanks you to let me know.
Cheers

PS: Here is a link about this issue.
https://inthecheesefactory.com/blog/things-you-need-to-know-about-android-m-permission-developer-edition/en
According to this link, it is possible to "solve" this issue by setting targetSdkVersion at a value less than 23 but google refuse to downgrade it during the upload. Please help. I'm stuck.

**Comment by myflashlab** [comment]
You don't need an ANE for Android permissions right now! Please read the [Handling Permissions on Android: section on this post](http://www.myflashlabs.com/understanding-android-ios-permissions-in-adobe-air-apps/).

> Today that I am writing this post, your apps being compiled even with Air SDK 22 beta (UPDATE: AIR 23 is also using an old version of Android SDK), will work just fine like before on Android 6 devices even if you are using dangerous permissions in your app

**Comment by marcanw** [comment]
Unfortunately I do have this issue.
The problem comes from targetSdkVersion that was at 23 and google refuse to downgrade to 22.
So my app is practically unusable on all the devices running android M.

**Comment by myflashlab** [comment]
Oh, I see. will you please drop my colleagues an email from http://www.myflashlabs.com/contact/ and link to this conversation? We don't have plans on upgrading the PermissionCheck ANE for Android as right now prior to Adobe AIR SDK upgrades to a newer Android version but maybe our colleagues can find a custom solution for you so you can get over the problem fast. Please continue your talks directly through email. Thanks. I'm closing this issue.
