### ISSUE TITLE
Not showing the Auth popup anymore.

### ISSUE THREAD

**Issue by Seb-AS** [myflashlab/PermissionCheck-ANE#4]
Hi,

After I don't allowed the camera, is not showing the dialog anymore.

Always showing "You did not allow the app the required permissions!"

The only solution I've found is openSettings() but the user is going out of the app. 

```
	function onRequestResult($state:int):void
			{
				if ($state != PermissionCheck.PERMISSION_GRANTED)
				{
					trace("You did not allow the app the required permissions!");
					
					_exPermissions.openSettings();
				}
				else
				{
					init();
				}
			}
```

IOS 10.1.1
Iphone 6s

**Comment by myflashlab** [comment]
Yes @Seb-AS This is how permissions work on iOS and there's nothing we can do about it. Apple decided things to work this way. **Note:** You don't have this problem on the Android side. So, you are correct, on the iOS, the only thing you can do after the dialog rejection is to open the setting menu.
