### ISSUE TITLE
"Implementation not found"

### ISSUE THREAD

**Issue by douglasmccarroll** [myflashlab/PermissionCheck-ANE#6]
Hi,

I'm getting the following message when I try to build an iOS version of my app:

An implementation for native extension 'com.myflashlab.extensions.nativePermissions' required by the application was not found for the target platform.

I have IntelliJ configured so that it 'sees' all of my other native extensions, i.e. I'm able to build without problems. And I've put this extension in the same folder, so I think that IntelliJ can probably see it also.

Actually, I imagine that IntelliJ is simply passing the folder location to the compiler, so its more a matter of the compiler 'seeing' the files, but the same principle applies.

Do you have any idea of what the problem is? I'm trying to get this working so that I can use your barcode extension with AIR 24.

Is there any other info that I can supply that will help you to help me?

Thanks,

Douglas

**Comment by myflashlab** [comment]
I guess, you are trying to run the ANE on a simulator? If so, please try to run on a real device. also make sure your manifest includes the following:

```xml
    <extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>

    <!-- The following dependency ANEs are only required when compiling for Android -->
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
```

**Comment by douglasmccarroll** [comment]
My mistake. I had this in my manifest:
<extensionID>com.myflashlab.air.extensions.nativePermissions</extensionID>
Which, of course, is incorrect.
Thanks much.  :)
